### ISSUE TITLE
Extension is completely broken! Error message: payload.data is not iterable when importing or exporting

### ISSUE THREAD

**Issue by jmoransi** [DawnbrandBots/deck-transfer-for-master-duel#15]
### Actual behaviour

When importing deck from Dueling book either using YDKE code or YDK file, an error message appears with the following message

payload.data is not iterable 

![image](https://github.com/DawnbrandBots/deck-transfer-for-master-duel/assets/4677018/ba0fa86c-1acc-4adb-afdb-8fc33dabbe96)

### Expected behaviour

1. Import YDK file
2. Deck should appear in official yugioh db

### Browser, and version if you know

Microsoft Edge Version 126.0.2592.56 (Official build) (64-bit)

### Operating system and version

Windows 11

**Comment by jmoransi** [comment]
Same YDK file can be imported into YGOProdeck website

![image](https://github.com/DawnbrandBots/deck-transfer-for-master-duel/assets/4677018/80a76b55-d0b2-40d4-91cd-78ac1d1a6ff7)

attaching YDK file
[LabJack3.zip](https://github.com/user-attachments/files/15893667/LabJack3.zip)

**Comment by kevinlul** [comment]
Thanks for reporting a bug! I have reproduced this issue and continue to investigate.
![image](https://github.com/DawnbrandBots/deck-transfer-for-master-duel/assets/6320810/345a7f3f-797b-4c3d-8427-26bbc92a0faf)

**Comment by kevinlul** [comment]
This problem is caused by a change in behaviour in the YGOPRODECK API. 
![image](https://github.com/DawnbrandBots/deck-transfer-for-master-duel/assets/6320810/5a8c04be-b632-42c0-a93b-b0b13c45c7bb)

This breaks all functionality of this extension, import and export, and is not specific to the provided deck.

**Comment by kevinlul** [comment]
I have reported this issue to the site owner, pending a response tomorrow. In the event that this change is behaviour is intended and permanent, I have also prepared a fix in the extension.

**Comment by kevinlul** [comment]
This should be resolved now.

**Comment by kevinlul** [comment]
Fix reconfirmed. Thanks again for reporting this. I'm currently working on automated tests in #10 that would catch this kind of error sooner.
